# Generated by Django 2.2.1 on 2019-06-30 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('apellidoPaterno', models.CharField(max_length=254)),
                ('apellidoMaterno', models.CharField(max_length=254)),
                ('carrera', models.CharField(max_length=254)),
                ('matricula', models.IntegerField()),
                ('rfid', models.CharField(max_length=254)),
                ('delete', models.BooleanField(default=False)),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Alumno',
            },
        ),
    ]
